# Generated by Django 6.1 on 2026-08-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile_studentprofile'),
        ('schools', '0003_assessment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Leave empty only for system operators.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.institution', verbose_name='school'),
        ),
    ]
