"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (git-ignored, never committed).
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    """Read a boolean from the environment. Only 'true'/'1'/'yes' mean True."""
    return os.getenv(name, str(default)).strip().lower() in ("true", "1", "yes")


# SECURITY: the secret key must come from the environment. Failing loudly here
# is deliberate — a missing key should stop the app, never fall back to a
# default that might silently reach production.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY: defaults to False, so forgetting to set it cannot expose debug
# pages and stack traces in production.
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # GradeVault
    "accounts",
    "schools",
    "audit",
]

# Must be set before the first migration. Swapping the user model later
# requires rebuilding the database, so it is declared here from the start.
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Must sit directly after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Selects the active language per request. Must sit after SessionMiddleware
    # and before CommonMiddleware.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite while developing, PostgreSQL in production. Which one is used
# is decided by whether DATABASE_URL is set, so the database is
# configuration rather than a code change.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if os.getenv("DATABASE_URL"):
    import dj_database_url

    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
        # Production requires TLS to the database. CI runs Postgres in a
        # container on a private network, so it sets DATABASE_SSL=False.
        ssl_require=env_bool("DATABASE_SSL", not DEBUG),
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

_PASSWORD_VALIDATION = "django.contrib.auth.password_validation"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_PASSWORD_VALIDATION}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.MinimumLengthValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.CommonPasswordValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"

# Languages GradeVault will be offered in. Somali translations are added in a
# later milestone, but declaring them now means every template written from
# here on uses translation tags rather than needing a retrofit.
LANGUAGES = [
    ("en", "English"),
    ("so", "Soomaali"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Somalia is UTC+3 and does not observe daylight saving. Timestamps are stored
# in UTC (USE_TZ) and rendered in local time.
TIME_ZONE = "Africa/Mogadishu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

# Source assets we author.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where `collectstatic` gathers files for the production web server.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves static files from the application process, so a small
# deployment needs no separate web server. Compresses and fingerprints
# them, which matters on the mobile connections most Somali users have.
#
# The manifest backend is used only in production, because it refuses to
# serve any file that collectstatic has not processed. That strictness is
# right for a deployment and wrong while developing, where it makes every
# page raise until collectstatic is run. CI runs collectstatic so the
# production path is still exercised on every push.

_STATIC_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": _STATIC_BACKEND},
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Authentication flow
# Signing in lands on the dashboard, which sends each role to its own area.

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Nothing in GradeVault sends email yet; password resets are done by an
# administrator. The configuration exists so that when something does
# send, it is not silently discarded.
#
# Set EMAIL_HOST to enable real delivery. Without it, mail is printed to
# the console, which is correct while developing and would be wrong in
# production — hence the check below.

if os.getenv("EMAIL_HOST"):
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "HOST": os.environ["EMAIL_HOST"],
            "PORT": int(os.getenv("EMAIL_PORT", "587")),
            "USER": os.getenv("EMAIL_HOST_USER", ""),
            "PASSWORD": os.getenv("EMAIL_HOST_PASSWORD", ""),
            "USE_TLS": env_bool("EMAIL_USE_TLS", True),
        },
    }
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", os.environ["EMAIL_HOST_USER"])
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }


# ============================================================
# Production hardening
# ============================================================
#
# These apply only when DEBUG is off, so local development is unaffected.
# Tying them to DEBUG rather than a separate flag means there is no way
# to deploy with them accidentally left off.
#
# This system holds educational records belonging to minors, so the
# defaults are strict rather than convenient.

if not DEBUG:
    # Refuse plain HTTP. Marks and names must never cross the network in
    # the clear, and Somali users are often on shared mobile networks.
    SECURE_SSL_REDIRECT = True

    # Render terminates TLS at its proxy and tells Django via this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Tell browsers to refuse plain HTTP for a year, including subdomains.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Session and CSRF cookies must never travel unencrypted.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # A session cookie readable by JavaScript is a session cookie one
    # cross-site scripting bug away from being stolen.
    SESSION_COOKIE_HTTPONLY = True

    # Do not let the browser guess a file's type; a guessed type is how
    # an uploaded file becomes an executed script.
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Refuse to be framed, so the login page cannot be overlaid.
    X_FRAME_OPTIONS = "DENY"

    # Referrer headers must not leak a student's page URL to other sites.
    SECURE_REFERRER_POLICY = "same-origin"

    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS if host and "*" not in host
    ]
