"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (git-ignored, never committed).
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    """Read a boolean from the environment. Only 'true'/'1'/'yes' mean True."""
    return os.getenv(name, str(default)).strip().lower() in ("true", "1", "yes")


# SECURITY: the secret key must come from the environment. Failing loudly here
# is deliberate — a missing key should stop the app, never fall back to a
# default that might silently reach production.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY: defaults to False, so forgetting to set it cannot expose debug
# pages and stack traces in production.
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Locks an account out after repeated failed sign-ins.
    "axes",
    # GradeVault
    "accounts",
    "schools",
    "audit",
]

# Must be set before the first migration. Swapping the user model later
# requires rebuilding the database, so it is declared here from the start.
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Must sit directly after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Selects the active language per request. Must sit after SessionMiddleware
    # and before CommonMiddleware.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Must be last: it wraps authentication to count failed attempts.
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite while developing, PostgreSQL in production. Which one is used
# is decided by whether DATABASE_URL is set, so the database is
# configuration rather than a code change.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if os.getenv("DATABASE_URL"):
    import dj_database_url

    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
        # Production requires TLS to the database. CI runs Postgres in a
        # container on a private network, so it sets DATABASE_SSL=False.
        ssl_require=env_bool("DATABASE_SSL", not DEBUG),
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

_PASSWORD_VALIDATION = "django.contrib.auth.password_validation"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_PASSWORD_VALIDATION}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.MinimumLengthValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.CommonPasswordValidator"},
    {"NAME": f"{_PASSWORD_VALIDATION}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"

# English only.
#
# A Somali option was offered and withdrawn: the switcher worked, but
# almost nothing was translated, so choosing it changed nothing visible.
# On a page arguing that this software can be trusted with children's
# records, a control that appears broken costs more than the feature was
# worth.
#
# The translation tags throughout the templates are deliberately kept.
# They cost nothing, and they mean Somali can return as finished work
# rather than as a button that half works.
LANGUAGES = [("en", "English")]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Somalia is UTC+3 and does not observe daylight saving. Timestamps are stored
# in UTC (USE_TZ) and rendered in local time.
TIME_ZONE = "Africa/Mogadishu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

# Source assets we author.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where `collectstatic` gathers files for the production web server.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves static files from the application process, so a small
# deployment needs no separate web server. Compresses and fingerprints
# them, which matters on the mobile connections most Somali users have.
#
# The manifest backend is used only in production, because it refuses to
# serve any file that collectstatic has not processed. That strictness is
# right for a deployment and wrong while developing, where it makes every
# page raise until collectstatic is run. CI runs collectstatic so the
# production path is still exercised on every push.

_STATIC_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": _STATIC_BACKEND},
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Authentication flow
# Signing in lands on the dashboard, which sends each role to its own area.

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Nothing in GradeVault sends email yet; password resets are done by an
# administrator. The configuration exists so that when something does
# send, it is not silently discarded.
#
# Set EMAIL_HOST to enable real delivery. Without it, mail is printed to
# the console, which is correct while developing and would be wrong in
# production — hence the check below.

if os.getenv("EMAIL_HOST"):
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "HOST": os.environ["EMAIL_HOST"],
            "PORT": int(os.getenv("EMAIL_PORT", "587")),
            "USER": os.getenv("EMAIL_HOST_USER", ""),
            "PASSWORD": os.getenv("EMAIL_HOST_PASSWORD", ""),
            "USE_TLS": env_bool("EMAIL_USE_TLS", True),
        },
    }
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", os.environ["EMAIL_HOST_USER"])
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }


# ============================================================
# Production hardening
# ============================================================
#
# These apply only when DEBUG is off, so local development is unaffected.
# Tying them to DEBUG rather than a separate flag means there is no way
# to deploy with them accidentally left off.
#
# This system holds educational records belonging to minors, so the
# defaults are strict rather than convenient.

if not DEBUG:
    # Refuse plain HTTP. Marks and names must never cross the network in
    # the clear, and Somali users are often on shared mobile networks.
    SECURE_SSL_REDIRECT = True

    # Render terminates TLS at its proxy and tells Django via this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Tell browsers to refuse plain HTTP for a year, including subdomains.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Session and CSRF cookies must never travel unencrypted.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # A session cookie readable by JavaScript is a session cookie one
    # cross-site scripting bug away from being stolen.
    SESSION_COOKIE_HTTPONLY = True

    # Do not let the browser guess a file's type; a guessed type is how
    # an uploaded file becomes an executed script.
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Refuse to be framed, so the login page cannot be overlaid.
    X_FRAME_OPTIONS = "DENY"

    # Referrer headers must not leak a student's page URL to other sites.
    SECURE_REFERRER_POLICY = "same-origin"

    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS if host and "*" not in host
    ]


# ============================================================
# Sign-in attempt limits
# ============================================================
#
# Without this, an attacker may guess a student's password without limit.
# Student usernames are predictable by design — STU-2026-0001 upwards —
# so guessing which accounts exist is trivial and only the password
# stands in the way.

AUTHENTICATION_BACKENDS = [
    # Must come first, so a locked-out attempt is refused before the
    # password is even checked.
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AXES_FAILURE_LIMIT = 10

# Ten attempts, then twenty minutes.
#
# Five was too strict for a school: students mistype, keyboards on shared
# machines are unfamiliar, and a child who has simply forgotten whether
# their password has a capital letter should not be shut out for an hour.
#
# Ten still stops guessing dead. A password worth having has far more
# than ten possibilities, so an attacker gains nothing from the extra
# five, while an honest student gets room to think.
#
# Twenty minutes is long enough to make automated guessing pointless and
# short enough that a student can wait out a lockout during one lesson
# rather than losing the day.
AXES_COOLOFF_TIME = timedelta(minutes=20)

# Lock the *combination* of address and username, not either alone.
#
# Locking by address would punish a whole school: Somali schools and
# internet cafés commonly share one public address, so one attacker
# would lock out every student behind it.
#
# Locking by username alone would let anyone lock a named student out
# deliberately by guessing wrong five times.
#
# The pair is narrow enough to stop guessing without becoming a weapon.
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]

# A successful sign-in clears the count, so yesterday's typos do not
# accumulate into tomorrow's lockout.
AXES_RESET_ON_SUCCESS = True

AXES_LOCKOUT_TEMPLATE = "lockout.html"

# Record the username tried, so an administrator can see which accounts
# are being probed. Never records what password was attempted.
AXES_VERBOSE = True


# ============================================================
# Logging
# ============================================================
#
# Without this, a production failure leaves nothing behind: the user sees
# an error page and the operator has no idea what happened. Logs go to
# standard output, which is where a hosted platform collects them.
#
# Two rules apply because this system holds children's records:
#
#   - request bodies are never logged, so a mistyped password or a mark
#     cannot end up in a log file
#   - failed sign-ins are logged loudly, because a run of them against
#     one account is the first sign of someone probing it

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "plain",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        # Server errors, including the traceback behind a 500 page.
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # Repeated failures against one account belong in the log.
        "axes": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Every SQL statement at DEBUG would include marks and names.
        # Left at WARNING deliberately.
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
