# Generated by Django 6.1 on 2026-08-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('score_recorded', 'Mark recorded'), ('score_changed', 'Mark changed'), ('score_cleared', 'Mark removed'), ('term_published', 'Results published'), ('term_unpublished', 'Results withdrawn')], max_length=32, verbose_name='action')),
                ('actor_label', models.CharField(help_text='Copied at the time, so the entry survives account deletion.', max_length=200, verbose_name='who')),
                ('student_label', models.CharField(blank=True, max_length=200, verbose_name='student')),
                ('classroom_label', models.CharField(blank=True, max_length=100, verbose_name='class')),
                ('subject_label', models.CharField(blank=True, max_length=120, verbose_name='subject')),
                ('assessment_label', models.CharField(blank=True, max_length=120, verbose_name='assessment')),
                ('term_label', models.CharField(blank=True, max_length=120, verbose_name='term')),
                ('old_value', models.CharField(blank=True, max_length=40, verbose_name='from')),
                ('new_value', models.CharField(blank=True, max_length=40, verbose_name='to')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='when')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit trail',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['student_label'], name='audit_audit_student_565469_idx')],
            },
        ),
    ]
