# Generated by Django 6.1 on 2026-08-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('schools', '0003_assessment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='schools.institution'),
        ),
    ]
