# Generated by Django 6.1 on 2026-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditlog_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("score_recorded", "Mark recorded"),
                    ("score_changed", "Mark changed"),
                    ("score_cleared", "Mark removed"),
                    ("term_published", "Results published"),
                    ("term_unpublished", "Results withdrawn"),
                    ("password_reset", "Password reset"),
                ],
                max_length=32,
                verbose_name="action",
            ),
        ),
    ]
