# Generated by Django 6.1 on 2026-08-18 08:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('short_name', models.CharField(help_text='Used on report cards where space is limited.', max_length=30, verbose_name='short name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='default scale')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='schools.institution')),
            ],
            options={
                'verbose_name': 'grading scale',
                'verbose_name_plural': 'grading scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. 2026/2027', max_length=20, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, help_text='The year new work defaults to. Only one may be current.', verbose_name='current year')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.institution')),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.institution')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. Term 1', max_length=40, verbose_name='name')),
                ('sequence', models.PositiveSmallIntegerField(help_text='1 for the first term, 2 for the second.', verbose_name='sequence')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_published', models.BooleanField(default=False, help_text='While unpublished, students cannot see any result for this term.', verbose_name='results published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.academicyear')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
                'ordering': ['academic_year', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. "Class 5" or "Form 2A"', max_length=50, verbose_name='name')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['academic_year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_class_name_per_year')],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5, verbose_name='letter')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='minimum percentage')),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='maximum percentage')),
                ('remark', models.CharField(blank=True, help_text='e.g. "Excellent"', max_length=100, verbose_name='remark')),
                ('points', models.DecimalField(blank=True, decimal_places=2, help_text='Reserved for GPA calculation. Not used in v1.', max_digits=4, null=True, verbose_name='points')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='schools.gradingscale')),
            ],
            options={
                'verbose_name': 'grade band',
                'verbose_name_plural': 'grade bands',
                'ordering': ['-min_percentage'],
                'constraints': [models.UniqueConstraint(fields=('scale', 'letter'), name='unique_letter_per_scale'), models.CheckConstraint(condition=models.Q(('max_percentage__gte', models.F('min_percentage'))), name='grade_band_max_not_below_min')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_scale_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_year_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_subject_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'sequence'), name='unique_term_sequence'),
        ),
    ]
