# Generated by Django 6.1 on 2026-08-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile_studentprofile'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('roll_number', models.PositiveSmallIntegerField(blank=True, help_text="The student's number within the class register.", null=True, verbose_name='roll number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'enrolment',
                'verbose_name_plural': 'enrolments',
                'ordering': ['classroom', 'roll_number', 'student'],
                'constraints': [models.UniqueConstraint(fields=('student', 'classroom'), name='unique_student_per_class')],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='schools.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='schools.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'teaching assignment',
                'verbose_name_plural': 'teaching assignments',
                'ordering': ['classroom', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'classroom'), name='unique_teaching_assignment')],
            },
        ),
    ]
