# Generated by Django 6.1 on 2026-08-18 12:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_enrollment_teachingassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. "Mid-term" or "Final"', max_length=60, verbose_name='name')),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='The total this assessment is marked out of, e.g. 40.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='out of')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Controls the order shown on a report card.', verbose_name='order')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.term')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['term', 'classroom', 'subject', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if the student has not been marked yet.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='marks')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='schools.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='schools.enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'ordering': ['assessment', 'enrollment'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('term', 'subject', 'classroom', 'name'), name='unique_assessment_per_subject_class_term'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='assessment_max_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('enrollment', 'assessment'), name='unique_score_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('marks__gte', 0), ('marks__isnull', True), _connector='OR'), name='score_not_negative'),
        ),
    ]
